### ISSUE TITLE
Unable to send email

### ISSUE THREAD

**Issue by apriendeau** [julianlam/nodebb-plugin-emailer-sendgrid#1]
8/6 21:25 [262] - [33mwarn[39m: [emailer.sendgrid] Unable to send `test` email to uid 2!!
8/6 21:25 [262] - [33mwarn[39m: [emailer.sendgrid] Error Stringified:{}
8/6 21:26 [262] - [33mwarn[39m: [emailer.sendgrid] Unable to send `test` email to uid 2!!
8/6 21:26 [262] - [33mwarn[39m: [emailer.sendgrid] Error Stringified:{}
8/6 21:29 [262] - [33mwarn[39m: [emailer.sendgrid] Unable to send `test` email to uid 2!!
8/6 21:29 [262] - [33mwarn[39m: [emailer.sendgrid] Error Stringified:{}
8/6 21:30 [262] - [33mwarn[39m: [emailer.sendgrid] Unable to send `test` email to uid 2!!
8/6 21:30 [262] - [33mwarn[39m: [emailer.sendgrid] Error Stringified:{}

This is sending a test email from the app.

**Comment by lukeschafer** [comment]
ditto

**Comment by kreutzwj** [comment]
Same issue

**Comment by kreutzwj** [comment]
Found my issue. The plugin doesn't let you choose port. By switching to a null user, the sendgrid module will use http for sending instead of using port 25. I will try creating a push request with my changes after I polish them up.

**Comment by julianlam** [comment]
Nice work, thanks @kreutzwj!

**Comment by lukeschafer** [comment]
Mine was different. I am using the azure account and I set up an api key via sendgrid on my auto-generated account, whereas I should have used the connection info provided through the azure UI.

The real problem was that sendgrid isn't bubbling up the actual error (which was an auth error). Not the plugin's fault :)

**Comment by julianlam** [comment]
Closed via #2
