### ISSUE TITLE
Broken in 0.8.x?

### ISSUE THREAD

**Issue by afm-sayem** [julianlam/nodebb-plugin-emailer-sendgrid#4]
NodeBB(0.8.x, mongodb backend)

The dashboard shows `Emailer not installed` in the status. I have been unable to send email even though provided all the configuration.

Getting this warning in events:
```5/10 12:03 [14] - warn: [plugins/load] The following plugins may not be compatible with your version of NodeBB. This may cause unintended behaviour or crashing. In the event of an unresponsive NodeBB caused by this plugin, run `./nodebb reset -p PLUGINNAME` to disable it.
[33m  * [39mnodebb-plugin-emailer-sendgrid```

**Comment by julianlam** [comment]
Install this plugin visit the ACP page not via npm.
