### ISSUE TITLE
[Bug] Always shows emailer not installed with sendgrid 1.1.3 and nodebb 0.8.2

### ISSUE THREAD

**Issue by luofan189** [julianlam/nodebb-plugin-emailer-sendgrid#5]
Hi,

I installed nodebb 0.8.2 and sendgrid emailer via ACP with the version 1.1.3, but no matter if I restart or reload the server, the status always shows "Emailler not installed"

Please help
Thanks,
Fan

**Comment by luofan189** [comment]
Any updates on this one? I had to end up to use the latest mandrill plugin to get the emailer working..

**Comment by julianlam** [comment]
Version 2.0.0 should work fine for this one.
