### ISSUE TITLE
Missing file "nodebb/build/public/templates/admin/plugins/emailer-sendgrid.tpl"

### ISSUE THREAD

**Issue by imnisen** [julianlam/nodebb-plugin-emailer-sendgrid#8]
Hi, 
when I install "sendgrid"  with `npm install nodebb-plugin-emailer-sendgrid` ,  then active the plugin in the admin panel, and restart nodebb. After that when I click the menu "plugins"-> "Emails(sendgrid)", error shows in the server terminal

```
2018-02-25T08:36:11.836Z [8165] - error: /assets/templates/admin/plugins/emailer-sendgrid.js
 Error: ENOENT: no such file or directory, open '/root/nodebb/build/public/templates/admin/plugins/emailer-sendgrid.tpl'
    at Error (native)
```

and what in `/root/nodebb/build/public/templates/admin/plugins`
```
root@ubuntu16:~/nodebb# ls /root/nodebb/build/public/templates/admin/plugins

composer-default.js  
composer-default.tpl  
emoji.js  
emoji.tpl  
markdown.tpl  
mentions.tpl  
persona.tpl
```

The weird thing is when I want to install other smtp plugin, similar things happens:

for example, install and use "nodebb-plugin-emailer-smtp", following errors shows:
```
2018-02-25T07:12:24.229Z [7052] - error: /assets/templates/admin/emailers/local.js
 Error: ENOENT: no such file or directory, open '/root/nodebb/build/public/templates/admin/emailers/local.tpl'
    at Error (native)
```
and when I check the directory, there is no `/root/nodebb/build/public/templates/admin/emailers` dir.

I think these may be same problems, perhaps due to some wrong config of my nodbb?

Environment Info:
server: ubuntu 16.04
nodebb version:v1.7.5
nodebb-plugin-emailer-sendgrid version : 2.1.4

Thanks very much!

**Comment by julianlam** [comment]
Hi there. When installing new plugins, please restart & build NodeBB via the admin panel dashboard, or run `./nodebb build` via the command line, _then_ restart via the command line.

**Comment by julianlam** [comment]
![selection_294](https://user-images.githubusercontent.com/923011/36644162-2b815d14-1a24-11e8-9673-9d698d6d95b9.png)

**Comment by imnisen** [comment]
Thanks very much, helps a lot!

**Comment by amit-kumaryadav** [comment]
Thanks @julianlam It's helps
